# homework 1
EXEC = hw3
SRCS = hw3.c shapes.c loadtexbmp.c
COMP = gcc
CFLG = -O3 -Wall -Wextra
LIBS = -lglut -lGLU -lGL -lm

all:
	$(COMP) -O3 $(CFLG) $(SRCS) $(LIBS) -o $(EXEC)
clean:
	rm -f *.o *.gch hw2
