# homework 1
EXEC = run
SRCS = proj.c framework.c shapes.c
COMP = gcc
CFLG = -O3 -Wall -Wextra
LIBS = -lglut -lGLU -lGL -lm

all:
	$(COMP) $(CFLG) $(SRCS) $(LIBS) -o $(EXEC)
clean:
	rm -f *.o *.gch run
